### ISSUE TITLE
Refused

### ISSUE THREAD

**Issue by yoenispantoja** [danisss9/ngx-ssrs-reportviewer-v2#1]
Refused to display 'my_server_url' in a frame because it set 'X-Frame-Options' to 'sameorigin

**Comment by danisss9** [comment]
Your report server url is returning a "X-Frame-Options" value that does not allow it to be embeded in other websites/apps. You have to remove this HTTP header from that report server to use this lib.

See more:
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)
