### ISSUE TITLE
Problems in Firefox

### ISSUE THREAD

**Issue by yoenispantoja** [danisss9/ngx-ssrs-reportviewer-v2#2]
Hello.. I'm using this wonderful tool in my project, (Angular version 14.2), and (SSRS ©2016 version 13.0). It working fine in Chrome, but in Mozilla Firefox the component render as empty (blank frame). How I can resolve it? Thanks

**Comment by danisss9** [comment]
Hello,

Thank you but@tycomo did the library not me, I only updated it to a more recent Angular version.

Did Firefox give any error on the console? Never had problems with firefox in my side.
